logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  jpa:
    showSql: false
  datasource:
    url: ${SPRING_JPA_DATASOURCE_URL}
    username: ${SPRING_JPA_DATASOURCE_USERNAME}
    password: ${SPRING_JPA_DATASOURCE_PASSWORD}

hibernate:
  jdbc:
    lob:
      non_contextual_creation: true
